PACKET Login_REQ_C2S
	string PID
END

PACKET Login_RES_S2C
	long USER_ID
	long ServerTimeUnix
	string SessionToken
	int CHANNEL_ID
END

PACKET Login_FIN_C2S
END

PACKET RestAPI_REQ_C2S
END

PACKET RestAPI_RES_S2C
	string Info
END